### ISSUE TITLE
Deriving copy for PeripheralID

### ISSUE THREAD

**Issue by ratmice** [deviceplug/btleplug#234]
From what I can tell, `PeripheralId` is a newtype around a platform defined type 

```
winrtble ~ PeripheralId(Uuid)
bluez | corebluetooth ~ PeripheralId(BDAddr)
```

It seems that both `BDAddr`, and `Uuid` types are copy,
So in theory it seems currently it is possible to make `PeripheralId` copy, as well.
I can't think of a reason why something which is truly just an Id shouldn't be copy, but perhaps i'm not creative enough.

So I figured i'd ask before just sending a PR if there is any reason or objections to making it so.

**Comment by qwandor** [comment]
On some other platforms it will be a larger type, e.g. the draft WebBluetooth implementation in https://github.com/deviceplug/btleplug/pull/204 uses a `String` for PeripheralId. I don't remember what the Android implementation was going to do. I was also thinking of changing the Linux implementation to use a wrapper around a string (the D-Bus path), because at the moment it has to convert back and forth all the time.

So although we could currently make `PeripheralId` implement `Copy`, I'd rather not do that now only to remove it again later when we add more platforms.
